### ISSUE TITLE
Send notifications to "workers" via email/text

### ISSUE THREAD

**Issue by GISjaclyn** [Esri/workforce-scripts#19]
It would be very helpful if Workers could receive notifications _outside_ of the application when new work is assigned to them. For a small organization where field workers aren't constantly interfacing with Esri apps, this type of function is near essential to help draw traffic to the Workforce application and complete critical work.

**Comment by apulverizer** [comment]
@GISjaclyn This is somewhat out of the scope of these example scripts as it is fairly custom behavior.

One possible solution would be to do something similar to the [Assignment Monitor](https://github.com/Esri/workforce-scripts/blob/master/assignment_monitor.md) script. The provided example script polls the assignment feature service to find newly completed assignment and then posts a message to Slack (chat application).

I think you could do something similar and monitor all assignments, when the status changed to assigned, then you could fetch the user info from the portal (which has their email), then you could send them an email using the built in Python smtp/email standard libraries.

**Comment by apulverizer** [comment]
There are couple solutions for this (which are out of scope for this repo):
1. Modify the assignment monitor script to send an email instead of posting to Slack. Run this on a server with a schedule or as a cloud/lambda function on AWS/Azure/Google Cloud
2. Leverage GeoEvent to process new assignments and send emails

Closing.
