### ISSUE TITLE
Standalone scripts - create_assignments_from_csv.py - Assignment Type field name

### ISSUE THREAD

**Issue by jonathancgroves** [Esri/workforce-scripts#23]
Enabling and inspection of the logger output from the above script reveals that the Assignment Type domain is defined in the feature layer (NB this is Enterprise Workforce) as follows:
`		'domain': {
			'codedValues': [{
				'code': 1, 'name': 'Urban cut'
			}, {
				'code': 2, 'name': 'Rural cut'
			}], 		'type': 'codedValue', 'name': 'assignments_42e8961a29c44340b914a69737817f41_ASSIGN_TYPE'
		}, 
		'name': 'assignmenttype', 'nullable': True, 'editable': True, 'alias': 'Assignment Type', 'type': 'esriFieldTypeInteger'
	}`
In the Python sample script supplied, the section for getting the codes of the domains includes:
`if field["name"] == "assignmentType":`
Changing this to `if field["name"] == "assignmenttype":` allows the search to be successful.

This worked fine with AGOL Workforce, I believe this may be a difference with Enterprise.
Hope this helps others.

Jonathan

**Comment by apulverizer** [comment]
This is a difference between Enterprise and AGOL (well really the backing databases). The scripts that use the Python API for ArcGIS handle the differences between the two correctly. 

We are essentially deprecating the scripts that use ArcREST and vanilla python in favor of using the Python API.

The Python API team recently added the API to PIP (which might be necessary since I don't think there is a conda build for Python 3 and ArmV6 architecture which your raspberry pi might have) so you can install it like `pip install arcgis` https://developers.arcgis.com/python/guide/install-and-set-up/#Install-using-pip.

I will update the documentation to highlight that only the scripts that use the Python API support Enterprise.

**Comment by jonathancgroves** [comment]
Bit of a bombshell there - so I need to both use the Python API and use Python 3.x instead of 2.7.1.
I'll have to wait and see if the Client will pay for this extra work.
Thanks for taking the time to look into this.

**Comment by apulverizer** [comment]
You are free to use/fork the standalone scripts, we just aren't going to update them anymore. Python 2.7.X is going to be sunsetted in 2020 so it'd be advisable to start moving to Python 3.X.
