### ISSUE TITLE
KeyError 'globalid'

### ISSUE THREAD

**Issue by cpsmhammond** [Esri/workforce-scripts#32]
Hey,

i'm getting and error when I run this on my enterprise install.  Copying assignments from workforce installed in portal to a feature service on the same server.  Any thoughts?  We have this working on the same layer on our previous server so I'm a bit stumped.

archived_assignments = target_fl.query(out_fields=field_mappings[project._assignment_schema.global_id]) | KeyError: 'globalid'

Thanks

**Comment by apulverizer** [comment]
@cpsmhammond 

My guess is the `field_mappings` dictionary does not have the "globalid" field. Perhaps it's "GlobalID" or "GlobalId"?

**Comment by cpsmhammond** [comment]
Thanks for that quick response.. that lead me down the right track.. mostly.  I had to adjust my mappings file so every key is lowercase, but the keys below don't work no matter what case i choose.. any other ideas? 

creationdate: CreationDate
Creator: Creator
EditDate: EditDate
Editor: Editor

Banging my head against the wall has not yet resulted in anything positive so I'm hopeful you can help out again! :)

Mark

**Comment by apulverizer** [comment]
Ah the wonders of Enterprise :)

The actual names of those fields is different between Online and Enterprise (due to how the feature service is implemented). If you look at the layer definition for assignments (json) for the assignments layer you will see those fields are defined as:

```
"editFieldsInfo": {
    "creationDateField": "created_date",
    "creatorField": "created_user",
    "editDateField": "last_edited_date",
    "editorField": "last_edited_user"
}
```

For example, try using `created_date` instead of `CreationDate`.

This is why in the Python API we provide the following property `project._assignment_schema.creation_date` to get the creation date field name, instead of hard-coding it to a string.

Hopefully that resolves your issue.

**Comment by cpsmhammond** [comment]
I owe you.  thank you.

**Comment by cpsmhammond** [comment]
I wonder if there are more changes with Enterprise?  I'm getting a "Geometry could not be set" now on line 121.

**Comment by apulverizer** [comment]
I haven't seen that error before. Do any of the assignments have missing or invalid geometries somehow?

**Comment by cpsmhammond** [comment]
> I haven't seen that error before. Do any of the assignments have missing or invalid geometries somehow?

I got it solved, script is working.

the assignment.geometry didn't have a spatialreference, i had to add 1 line of code to update it with 4326 which is what we use.

after line 103
`assignment.geometry = dict(x=float(assignment.geometry["x"]),y=float(assignment.geometry["y"]),spatialReference=dict(wkid=int(4326)))`

Thanks

**Comment by apulverizer** [comment]
Closing since this was resolved.
