### ISSUE TITLE
AssignmentType shows GUID rather than text Alias in ArcGIS Pro

### ISSUE THREAD

**Issue by langdonms** [Esri/workforce-scripts#74]
**Describe the bug**
New Workforce Projects AssignmentType field values in the Assignment layer display the GUID value rather than a human readable text value when the feature service is displayed in ArcGIS Pro. I was hoping to use Append in Pro to migrate assignments from V1 to V2 but found this issue.

**To Reproduce**
1.  Migrate V1 to V2 project or create a new Project
2.  Create assignment types
3.  Add assignment layer to an ArcGIS Pro map and start editing
4.  In Attribute window, GUID values are shown rather than human readable aliases

![image](https://user-images.githubusercontent.com/7000206/91479657-c9a0e480-e86f-11ea-8c0c-c966481d3628.png)

**Comment by langdonms** [comment]
Also, for automation, does the https://developers.arcgis.com/python/api-reference/arcgis.apps.workforce.html work with V2 projects?

**Comment by apulverizer** [comment]
@langdonms This is because the assignment types are stored in a separate table and are not a coded value domain. This was an intentional decision to support assignment type changes when projects are offline and need to sync changes. There's no good way to resolve this in Pro unfortunately. 

The referenced api does work but you need to use the 1.8.3 pre-release version of the ArcGIS API for Python which is backwards compatible with older projects. This can be installed using `conda install -c esri/label/prerelease -c esri arcgis`

**Comment by langdonms** [comment]
Thanks for the quick reply and explanation @apulverizer I had hoped to do an append with field mapping to migrate & load new assignments but I'll take a closer look at the migrate script then. 👍 

Follow-up Q: 
Do you need to be the owner of the project to perform the scripts or can any admin account work? I say this bc my main account is authenticated through our G-Suite which might be a pain to use in the scripts while we have other automation accounts that are named user on AGOL. I'd prefer to keep myself as the owner of the projects for convenience but can change ownership if needed for the scripts to auth with a named user.

**Comment by apulverizer** [comment]
@langdonms you need to be a dispatcher in the project in order to use the Workforce module in the Python API. You could add your admin user as a dispatcher to the project and then should be able to do everything.

**Comment by apulverizer** [comment]
Closing, feel free to re-open needed.
