### ISSUE TITLE
Can't Assign Work: ValidationError: Assignment must have geometry

### ISSUE THREAD

**Issue by r3cyclops** [Esri/workforce-scripts#87]
**Describe the bug**
I can create assignments but when I go to assign the assignments to a specific user I get this error: ValidationError: Assignment must have geometry

**To Reproduce**
Here's my code:

user = project.workers.get(user_id="username")
test_backflows = project.assignment_types.get(name="Test Backflow Device")
assignments = project.assignments.search(f"status=0 AND assignmentType={test_backflows.code}")
for assignment in assignments:
    assignment.worker = user
    assignment.status = "assigned"
    assignment.assigned_date = datetime.datetime.utcnow()
assignments = project.assignments.batch_update(assignments)

**Comment by apulverizer** [comment]
@cgens how are you creating assignments?

**Comment by r3cyclops** [comment]
@apulverizer I'm creating them based off an existing map service. I could assign work for a couple iterations and then it started throwing the ValidationError. Here's my code:

for _, row in backflow_df.iterrows():
    backflow_assignments.append(
        workforce.Assignment(
            project,
            geometry=row["SHAPE"],
            location=row["Address"],
            description=row["Location"],
            assignment_type="Test Backflow Device",
            status="unassigned",
            due_date=pd.to_datetime(row.DueDate)
        )
    )
project.assignments.batch_add(backflow_assignments)

**Comment by apulverizer** [comment]
@cgens it's hard to say exactly what the problem is. My guess is that there is some feature in the dataframe that does not have a geometry so `row["SHAPE"]` is returning `None` which is then not setting a geometry for that assignment. When you call `batch_add` it validates each assignment object and the one that has `None` geometry is raising the validation exception. 

It might be useful to print the `row["SHAPE"]` while iterating to see if my guess is correct.

`

**Comment by r3cyclops** [comment]
@apulverizer That was it! Thank you.
